przymiotniki_k = [
    'szalona',
    'dziwna',
    'piękna',
    'okrutna',
    'zielona',
    'niezrozumiała',
    'nieznośna',
    'spragniona',
    'głodna',
    'niewyspana',
    'rozczochrana',
    'ułożona'
]
przymiotniki_n = [
    'szalone',
    'dziwne',
    'piękne',
    'okrutne',
    'zielone',
    'niezrozumiałe',
    'nieznośne',
    'spragnione',
    'złote',
    'smutne',
    'wesołe',
    'miłe',
    'brązowe',
    'niebieskie',
    'słoneczne'
]